require('pixel/cursorline').setup()
require('pixel/tabspace').setup()
require('pixel/colorsigns').setup()
require('pixel/complete').setup()
-- require('pixel/lightline')
-- require('pixel/nvim-tree')
-- require('pixel/nvim-cmp')
-- require('pixel/colorizer')
-- require('pixel/dap')
-- require('pixel/context')
-- require('pixel/lsp-lines')
-- require('pixel/lspsaga')
-- require('pixel/sessions')
-- require('autocompletion.lua')

